<?php

namespace Blogger\BlogBundle\Repository;

/**
 * BookReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookReviewRepository extends \Doctrine\ORM\EntityRepository
{
}
